// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Log struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ApiType   string
	CreatedAt sql.NullTime
	Comments  sql.NullString
}

type Session struct {
	ID      string
	UserID  string
	Data    pqtype.NullRawMessage
	Expires time.Time
}

type User struct {
	ID          uuid.UUID
	Email       string
	Name        string
	DisplayName string
	Credentials json.RawMessage
	GoogleID    string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	ApiKey      sql.NullString
	ApiKeyDev   sql.NullString
}
